//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myop_ihm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compte
    {
        public int Id { get; set; }
        public string nom_de_compte { get; set; }
        public string mot_de_passe { get; set; }
        public Nullable<int> administrateur_id { get; set; }
        public Nullable<int> pizzeria_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<bool> actif { get; set; }
    
        public virtual administrateur administrateur { get; set; }
        public virtual client client { get; set; }
        public virtual pizzeria pizzeria { get; set; }
    }
}
