//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myop_ihm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class composition_menu
    {
        public int menu_id { get; set; }
        public int pizza_id { get; set; }
        public int produits_id { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual pizza pizza { get; set; }
        public virtual produits produits { get; set; }
    }
}
