//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myop_ihm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class horaires
    {
        public int Id { get; set; }
        public int pizzeria_id { get; set; }
        public string jour { get; set; }
        public Nullable<System.TimeSpan> ouverture_matin { get; set; }
        public Nullable<System.TimeSpan> fermeture_matin { get; set; }
        public Nullable<System.TimeSpan> ouverture_soir { get; set; }
        public Nullable<System.TimeSpan> fermeture_soir { get; set; }
    
        public virtual pizzeria pizzeria { get; set; }
    }
}
