//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myop_ihm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pizzeria
    {
        public pizzeria()
        {
            this.commande = new HashSet<commande>();
            this.compte = new HashSet<compte>();
            this.horaires = new HashSet<horaires>();
            this.ingredients = new HashSet<ingredients>();
            this.pizza = new HashSet<pizza>();
            this.produits = new HashSet<produits>();
            this.type = new HashSet<type>();
        }
    
        public int Id { get; set; }
        public string nom { get; set; }
        public string nom_proprietaire { get; set; }
        public string prenom_proprietaire { get; set; }
        public string adresse { get; set; }
        public string adresse_de_facturation { get; set; }
        public string email { get; set; }
        public string no_telephone { get; set; }
    
        public virtual ICollection<commande> commande { get; set; }
        public virtual ICollection<compte> compte { get; set; }
        public virtual ICollection<horaires> horaires { get; set; }
        public virtual ICollection<ingredients> ingredients { get; set; }
        public virtual ICollection<pizza> pizza { get; set; }
        public virtual ICollection<produits> produits { get; set; }
        public virtual ICollection<type> type { get; set; }
    }
}
