//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myop_ihm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorie
    {
        public categorie()
        {
            this.ingredients = new HashSet<ingredients>();
            this.produits = new HashSet<produits>();
        }
    
        public int Id { get; set; }
        public string nom { get; set; }
    
        public virtual ICollection<ingredients> ingredients { get; set; }
        public virtual ICollection<produits> produits { get; set; }
    }
}
