//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myop_ihm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public commande()
        {
            this.menu = new HashSet<menu>();
            this.pizza = new HashSet<pizza>();
            this.produits = new HashSet<produits>();
        }
    
        public int Id { get; set; }
        public int no_Commande { get; set; }
        public int client_id { get; set; }
        public int pizzeria_id { get; set; }
        public System.DateTime date_commande { get; set; }
        public Nullable<System.TimeSpan> heure_livraison { get; set; }
        public Nullable<bool> livriaison { get; set; }
        public string Commentaire { get; set; }
    
        public virtual client client { get; set; }
        public virtual pizzeria pizzeria { get; set; }
        public virtual ICollection<menu> menu { get; set; }
        public virtual ICollection<pizza> pizza { get; set; }
        public virtual ICollection<produits> produits { get; set; }
    }
}
