//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myop_ihm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MYOPEntities : DbContext
    {
        public MYOPEntities()
            : base("name=MYOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrateur> administrateur { get; set; }
        public virtual DbSet<categorie> categorie { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commande> commande { get; set; }
        public virtual DbSet<compte> compte { get; set; }
        public virtual DbSet<description> description { get; set; }
        public virtual DbSet<horaires> horaires { get; set; }
        public virtual DbSet<ingredients> ingredients { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<pizza> pizza { get; set; }
        public virtual DbSet<pizzeria> pizzeria { get; set; }
        public virtual DbSet<produits> produits { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<composition_menu> composition_menu { get; set; }
    }
}
