SET IDENTITY_INSERT [dbo].[produits] ON
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (1, N'chesse buger', 9, 1, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (2, N'royal chesse', 9, 1, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (3, N'triple chesse', 9, 1, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (4, N'filet o fish', 9, 1, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (5, N'giant', 9, 2, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (6, N'giant supreme', 9, 2, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (7, N'spicy burger', 9, 2, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (8, N'chicken burger', 9, 2, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (9, N'demoniaque', 9, 1, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (10, N'cheezy burger', 9, 1, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (11, N'cht''ti burger', 9, 4, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (12, N'l''authentique', 9, 4, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (13, N'big nuggets', 10, 4, CAST(1.00 AS Decimal(4, 2)), 1, 10)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (14, N'mac cordon', 9, 4, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (15, N'defi', 9, 1, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (16, N'wrap jambon', 9, 3, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (17, N'wrap saumon', 9, 3, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (18, N'wrap poulet', 9, 3, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (19, N'wrap viande hachée', 9, 3, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (20, N'wrap thon', 9, 3, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (21, N'wrap 4 fromages', 9, 3, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (22, N'wrap merguez', 9, 3, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (23, N'wrap banane', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 8)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (24, N'wrap fraise', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 8)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (26, N'wrap coco', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 8)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (27, N'wrap banane coco', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 8)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (28, N'wrap banane pecan', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 8)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (29, N'wrap poire caramel', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 8)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (30, N'wrap ananas amande', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 8)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (31, N'wrap cerise amande', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 8)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (32, N'panini jambon', 9, 5, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (33, N'panini thon', 9, 5, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (34, N'panini poulet', 9, 5, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (35, N'panini saumon', 9, 5, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (36, N'panini 4 fromages', 9, 5, CAST(1.00 AS Decimal(4, 2)), 1, 9)
INSERT INTO [dbo].[produits] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (37, N'panini nutella', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
SET IDENTITY_INSERT [dbo].[produits] OFF
