SET IDENTITY_INSERT [dbo].[ingredients] ON
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (2, N'tomates', 1, 1, CAST(0.02 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (9, N'mozzarella', 11, 1, CAST(1.50 AS Decimal(4, 2)), 1, 2)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (10, N'champignon', 1, 1, CAST(3.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (11, N'olives', 12, 1, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (12, N'jambon', 5, 1, CAST(1.50 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (15, N'merguez', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (17, N'poivrons', 1, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (18, N'oignons frits', 1, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (19, N'oignons', 1, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (20, N'thon', 6, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (21, N'anchois', 6, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (22, N'steack haché', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (23, N'cheddar', 11, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (24, N'oeuf', 6, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (25, N'saumon fumé', 6, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (26, N'bleu', 11, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (27, N'chèvre', 11, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (28, N'pepperoni', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (29, N'poulet', 6, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (30, N'poulet fumé', 6, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (31, N'cordon bleu', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (32, N'sauce blanche', 4, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (33, N'pomme de terre', 1, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (34, N'lardons', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (35, N'viande kebab', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (36, N'créme fraiche', 4, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (37, N'mimolette', 11, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (38, N'sauce tomate', 4, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (39, N'viande hachée', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (40, N'fromage à raclette', 11, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (41, N'boursin', 11, 1, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (42, N'vache qui rit', 11, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (43, N'chorizo', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (44, N'harissa', 4, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (45, N'piment', 12, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (46, N'sauce barbecue', 4, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (47, N'sauce thaï', 4, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (48, N'sauce biggy', 4, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (49, N'maroilles', 11, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (50, N'anchois', 6, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (51, N'sauce nutella', 4, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (52, N'banane', 2, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (53, N'noix de coco', 2, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (54, N'ananas', 2, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (55, N'oreo', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (56, N'm&ms', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (57, N'lion', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (58, N'snickers', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (59, N'kinder bueno', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (60, N'milka', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (61, N'bounty', 8, 1, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (62, N'guimauve', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (63, N'mars', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (64, N'chocobon', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (65, N'fraise', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (66, N'amande', 2, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (67, N'sucre glace', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (68, N'speculoos', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (69, N'kitkat', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (70, N'galak', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (71, N'smarties', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (72, N'chocolat menthe', 8, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (73, N'jalapenos', 10, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (74, N'artichauts', 1, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (75, N'tomates sechées', 1, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (76, N'viande hachée bolognaise', 5, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (77, N'pate simple', 3, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (78, N'pate soufflée', 3, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (79, N'pate fourrée', 3, 1, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (81, N'mozzarella', 11, 2, CAST(2.00 AS Decimal(4, 2)), 1, 2)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (82, N'champignon', 1, 2, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (83, N'olives', 12, 2, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (84, N'jambon', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (85, N'merguez', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (86, N'poivrons', 1, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (87, N'oignons frits', 1, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (88, N'oignons', 1, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (89, N'thon', 6, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (90, N'anchois', 6, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (91, N'steack haché', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (92, N'cheddar', 11, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (93, N'oeuf', 6, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (94, N'saumon fumé', 6, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (95, N'bleu', 11, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (96, N'chèvre', 11, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (97, N'pepperoni', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (98, N'poulet', 6, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (99, N'poulet fumé', 6, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (100, N'cordon bleu', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (101, N'sauce blanche', 4, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (102, N'pomme de terre', 1, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (103, N'lardons', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (104, N'viande kebab', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (105, N'créme fraiche', 4, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (106, N'mimolette', 11, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (107, N'sauce tomate', 4, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (108, N'viande hachée', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (109, N'fromage à raclette', 11, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (110, N'boursin', 11, 2, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (111, N'vache qui rit', 11, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (112, N'chorizo', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (113, N'harissa', 4, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (114, N'piment', 12, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (115, N'sauce barbecue', 4, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (116, N'sauce thaï', 4, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (117, N'sauce biggy', 4, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (118, N'maroilles', 11, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (119, N'anchois', 6, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (120, N'sauce nutella', 4, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (121, N'banane', 2, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (122, N'noix de coco', 2, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (123, N'ananas', 2, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (124, N'oreo', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (125, N'm&ms', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (126, N'lion', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (127, N'snickers', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (128, N'kinder bueno', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (129, N'milka', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (130, N'bounty', 8, 2, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (131, N'guimauve', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (132, N'mars', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (133, N'chocobon', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (134, N'fraise', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (135, N'amande', 2, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (136, N'sucre glace', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (137, N'speculoos', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (138, N'kitkat', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (139, N'galak', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (140, N'smarties', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (141, N'chocolat menthe', 8, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (142, N'jalapenos', 10, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (143, N'artichauts', 1, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (144, N'tomates sechées', 1, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (145, N'viande hachée bolognaise', 5, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (146, N'pate simple', 3, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (147, N'pate soufflée', 3, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (148, N'pate fourrée', 3, 2, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (151, N'mozzarella', 11, 3, CAST(2.00 AS Decimal(4, 2)), 1, 2)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (152, N'champignon', 1, 3, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (153, N'olives', 12, 3, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (154, N'jambon', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (155, N'merguez', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (156, N'poivrons', 1, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (157, N'oignons frits', 1, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (158, N'oignons', 1, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (159, N'thon', 6, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (160, N'anchois', 6, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (161, N'steack haché', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (162, N'cheddar', 11, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (163, N'oeuf', 6, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (164, N'saumon fumé', 6, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (165, N'bleu', 11, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (166, N'chèvre', 11, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (167, N'pepperoni', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (168, N'poulet', 6, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (169, N'poulet fumé', 6, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (170, N'cordon bleu', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (171, N'sauce blanche', 4, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (172, N'pomme de terre', 1, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (173, N'lardons', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (174, N'viande kebab', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (175, N'créme fraiche', 4, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (176, N'mimolette', 11, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (177, N'sauce tomate', 4, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (178, N'viande hachée', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (179, N'fromage à raclette', 11, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (180, N'boursin', 11, 3, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (181, N'vache qui rit', 11, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (182, N'chorizo', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (183, N'harissa', 4, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (184, N'piment', 12, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (185, N'sauce barbecue', 4, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (186, N'sauce thaï', 4, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (187, N'sauce biggy', 4, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (188, N'maroilles', 11, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (189, N'anchois', 6, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (190, N'sauce nutella', 4, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (191, N'banane', 2, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (192, N'noix de coco', 2, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (193, N'ananas', 2, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (194, N'oreo', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (195, N'm&ms', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (196, N'lion', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (197, N'snickers', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (198, N'kinder bueno', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (199, N'milka', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (200, N'bounty', 8, 3, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (201, N'guimauve', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (202, N'mars', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (203, N'chocobon', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (204, N'fraise', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (205, N'amande', 2, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (206, N'sucre glace', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (207, N'speculoos', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (208, N'kitkat', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (209, N'galak', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (210, N'smarties', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (211, N'chocolat menthe', 8, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (212, N'jalapenos', 10, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (213, N'artichauts', 1, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (214, N'tomates sechées', 1, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (215, N'viande hachée bolognaise', 5, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (216, N'pate simple', 3, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (217, N'pate soufflée', 3, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (218, N'pate fourrée', 3, 3, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (221, N'mozzarella', 11, 4, CAST(2.00 AS Decimal(4, 2)), 1, 2)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (222, N'champignon', 1, 4, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (223, N'olives', 12, 4, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (224, N'jambon', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (225, N'merguez', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (226, N'poivrons', 1, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (227, N'oignons frits', 1, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (228, N'oignons', 1, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (229, N'thon', 6, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (230, N'anchois', 6, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (231, N'steack haché', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (232, N'cheddar', 11, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (233, N'oeuf', 6, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (234, N'saumon fumé', 6, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (235, N'bleu', 11, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (236, N'chèvre', 11, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (237, N'pepperoni', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (238, N'poulet', 6, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (239, N'poulet fumé', 6, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (240, N'cordon bleu', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (241, N'sauce blanche', 4, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (242, N'pomme de terre', 1, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (243, N'lardons', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (244, N'viande kebab', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (245, N'créme fraiche', 4, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (246, N'mimolette', 11, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (247, N'sauce tomate', 4, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (248, N'viande hachée', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (249, N'fromage à raclette', 11, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (250, N'boursin', 11, 4, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (251, N'vache qui rit', 11, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (252, N'chorizo', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (253, N'harissa', 4, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (254, N'piment', 12, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (255, N'sauce barbecue', 4, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (256, N'sauce thaï', 4, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (257, N'sauce biggy', 4, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (258, N'maroilles', 11, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (259, N'anchois', 6, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (260, N'sauce nutella', 4, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (261, N'banane', 2, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (262, N'noix de coco', 2, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (263, N'ananas', 2, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (264, N'oreo', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (265, N'm&ms', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (266, N'lion', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (267, N'snickers', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (268, N'kinder bueno', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (269, N'milka', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (270, N'bounty', 8, 4, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (271, N'guimauve', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (272, N'mars', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (273, N'chocobon', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (274, N'fraise', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (275, N'amande', 2, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (276, N'sucre glace', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (277, N'speculoos', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (278, N'kitkat', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (279, N'galak', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (280, N'smarties', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (281, N'chocolat menthe', 8, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (282, N'jalapenos', 10, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (283, N'artichauts', 1, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (284, N'tomates sechées', 1, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (285, N'viande hachée bolognaise', 5, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (286, N'pate simple', 3, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (287, N'pate soufflée', 3, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (288, N'pate fourrée', 3, 4, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (291, N'mozzarella', 11, 5, CAST(2.00 AS Decimal(4, 2)), 1, 2)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (292, N'champignon', 1, 5, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (293, N'olives', 12, 5, CAST(2.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (294, N'jambon', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (295, N'merguez', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (296, N'poivrons', 1, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (297, N'oignons frits', 1, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (298, N'oignons', 1, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (299, N'thon', 6, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (300, N'anchois', 6, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (301, N'steack haché', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (302, N'cheddar', 11, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (303, N'oeuf', 6, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (304, N'saumon fumé', 6, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (305, N'bleu', 11, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (306, N'chèvre', 11, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (307, N'pepperoni', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (308, N'poulet', 6, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (309, N'poulet fumé', 6, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (310, N'cordon bleu', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (311, N'sauce blanche', 4, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (312, N'pomme de terre', 1, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (313, N'lardons', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (314, N'viande kebab', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (315, N'créme fraiche', 4, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (316, N'mimolette', 11, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (317, N'sauce tomate', 4, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (318, N'viande hachée', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (319, N'fromage à raclette', 11, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (320, N'boursin', 11, 5, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (321, N'vache qui rit', 11, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (322, N'chorizo', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (323, N'harissa', 4, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (324, N'piment', 12, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (325, N'sauce barbecue', 4, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (326, N'sauce thaï', 4, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (327, N'sauce biggy', 4, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (328, N'maroilles', 11, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (329, N'anchois', 6, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (330, N'sauce nutella', 4, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (331, N'banane', 2, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (332, N'noix de coco', 2, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (333, N'ananas', 2, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (334, N'oreo', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (335, N'm&ms', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (336, N'lion', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (337, N'snickers', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (338, N'kinder bueno', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (339, N'milka', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (340, N'bounty', 8, 5, CAST(11.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (341, N'guimauve', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (342, N'mars', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (343, N'chocobon', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (344, N'fraise', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (345, N'amande', 2, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (346, N'sucre glace', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (347, N'speculoos', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (348, N'kitkat', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (349, N'galak', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (350, N'smarties', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (351, N'chocolat menthe', 8, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (352, N'jalapenos', 10, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (353, N'artichauts', 1, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (354, N'tomates sechées', 1, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (355, N'viande hachée bolognaise', 5, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (356, N'pate simple', 3, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (357, N'pate soufflée', 3, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
INSERT INTO [dbo].[ingredients] ([Id], [nom], [categorie_id], [pizzeria_id], [prix], [disponible], [description_id]) VALUES (358, N'pate fourrée', 3, 5, CAST(1.00 AS Decimal(4, 2)), 1, 1)
SET IDENTITY_INSERT [dbo].[ingredients] OFF
